version: '3'

services:
  django:
    env_file:
      - placesremember/.env
    image: 'g0tem/placesremember'
    build: .
    container_name: places
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'